// //name, roll, age, class, gender, location, Admission fees

// const students = [
//   {
//     id: 1,
//     name: "montaj",
//     age: 19,
//     class: 12,
//     roll: 34,
//     gender: "male",
//     location: "howrah",
//     Admission_fees: 550,
//   },
//   {
//     id: 2,
//     name: "mon",
//     age: 17,
//     class: 11,
//     roll: 34,
//     gender: "male",
//     location: "birshibpur",
//     Admission_fees: 500,
//   },
//   {
//     id: 3,
//     name: "rima",
//     age: 19,
//     class: 12,
//     roll: 39,
//     gender: "female",
//     location: "fulusware",
//     Admission_fees: 550,
//   },
//   {
//     id: 4,
//     name: "eliza",
//     age: 15,
//     class: 9,
//     roll: 14,
//     gender: "female",
//     location: "uluberia",
//     Admission_fees: 300,
//   },
//   {
//     id: 5,
//     name: "montajul",
//     age: 16,
//     class: 10,
//     roll: 43,
//     gender: "male",
//     location: "mohespur",
//     Admission_fees: 450,
//   },
//   {
//     id: 6,
//     name: "monisha",
//     age: 20,
//     class: 13,
//     roll: 34,
//     gender: "female",
//     location: "goruhata",
//     Admission_fees: 350,
//   },
//   {
//     id: 7,
//     name: "mymunah",
//     age: 7,
//     class: 3,
//     roll: 24,
//     gender: "female",
//     location: "baragohal",
//     Admission_fees: 990,
//   },
//   {
//     id: 8,
//     name: "sameya",
//     age: 5,
//     class: 2,
//     roll: 17,
//     gender: "female",
//     location: "dokangora",
//     Admission_fees: 250,
//   },
//   {
//     id: 9,
//     name: "monjur",
//     age: 9,
//     class: 4,
//     roll: 11,
//     gender: "male",
//     location: "nolpur",
//     Admission_fees: 750,
//   },
//   {
//     id: 10,
//     name: "ramu",
//     age: 13,
//     class: 8,
//     roll: 44,
//     gender: "male",
//     location: "bagnan",
//     Admission_fees: 850,
//   },
//   {
//     id: 11,
//     name: "kazi",
//     age: 14,
//     class: 7,
//     roll: 53,
//     gender: "male",
//     location: "bainan",
//     Admission_fees: 430,
//   },
//   {
//     id: 12,
//     name: "abir",
//     age: 20,
//     class: 12,
//     roll: 54,
//     gender: "male",
//     location: "uluberia",
//     Admission_fees: 550,
//   },
//   {
//     id: 13,
//     name: "rafiya",
//     age: 19,
//     class: 12,
//     roll: 89,
//     gender: "female",
//     location: "gongarampur",
//     Admission_fees: 150,
//   },
//   {
//     id: 14,
//     name: "mustra",
//     age: 16,
//     class: 9,
//     roll: 64,
//     gender: "female",
//     location: "nolpur",
//     Admission_fees: 520,
//   },
//   {
//     id: 15,
//     name: "moon",
//     age: 35,
//     class: 15,
//     roll: 34,
//     gender: "male",
//     location: "kolkata",
//     Admission_fees: 650,
//   },
//   {
//     id: 16,
//     name: "monika",
//     age: 22,
//     class: 15,
//     roll: 123,
//     gender: "female",
//     location: "amtola",
//     Admission_fees: 430,
//   },
//   {
//     id: 17,
//     name: "raju",
//     age: 3,
//     class: 1,
//     roll: 4,
//     gender: "male",
//     location: "howrah",
//     Admission_fees: 1550,
//   },
//   {
//     id: 18,
//     name: "gita",
//     age: 12,
//     class: 6,
//     roll: 13,
//     gender: "female",
//     location: "abada",
//     Admission_fees: 120,
//   },
//   {
//     id: 19,
//     name: "babulal",
//     age: 23,
//     class: 15,
//     roll: 87,
//     gender: "male",
//     location: "baragohal",
//     Admission_fees: 890,
//   },
//   {
//     id: 20,
//     name: "intajul",
//     age: 19,
//     class: 13,
//     roll: 31,
//     gender: "male",
//     location: "narkaltola",
//     Admission_fees: 550,
//   },
//   {
//     id: 21,
//     name: "inamul",
//     age: 19,
//     class: 12,
//     roll: 65,
//     gender: "male",
//     location: "kalitola",
//     Admission_fees: 550,
//   },
//   {
//     id: 22,
//     name: "azijul",
//     age: 12,
//     class: 5,
//     roll: 34,
//     gender: "male",
//     location: "howrah",
//     Admission_fees: 550,
//   },
//   {
//     id: 23,
//     name: "monu",
//     age: 23,
//     class: 14,
//     roll: 85,
//     gender: "male",
//     location: "howrah",
//     Admission_fees: 550,
//   },
//   {
//     id: 24,
//     name: "kalam",
//     age: 15,
//     class: 10,
//     roll: 35,
//     gender: "male",
//     location: "howrah",
//     Admission_fees: 550,
//   },
//   {
//     id: 25,
//     name: "rani",
//     age: 19,
//     class: 11,
//     roll: 63,
//     gender: "female",
//     location: "howrah",
//     Admission_fees: 550,
//   },
//   {
//     id: 26,
//     name: "ruma",
//     age: 20,
//     class: 13,
//     roll: 98,
//     gender: "female",
//     location: "howrah",
//     Admission_fees: 550,
//   },
//   {
//     id: 27,
//     name: "hapijul",
//     age: 11,
//     class: 7,
//     roll: 62,
//     gender: "male",
//     location: "hugli",
//     Admission_fees: 234,
//   },
//   {
//     id: 28,
//     name: "mafuja",
//     age: 19,
//     class: 12,
//     roll: 97,
//     gender: "female",
//     location: "mondolPara",
//     Admission_fees: 760,
//   },
//   {
//     id: 29,
//     name: "raja",
//     age: 20,
//     class: 13,
//     roll: 243,
//     gender: "male",
//     location: "howrah",
//     Admission_fees: 550,
//   },
//   {
//     id: 30,
//     name: "porimone",
//     age: 18,
//     class: 11,
//     roll: 1,
//     gender: "female",
//     location: "bangladash",
//     Admission_fees: 1234,
//   },
// ];

/**
 * - Total Admnission fees
- Find All Female Students
- Find class wise student result
- Location wise student result
- find student between 10 - 25 age 
 */


const datasave = JSON.stringify(davs);

document.cookie =` montaj = ${datasave}`;

